import { sql } from "drizzle-orm";
import { integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const members = sqliteTable("members", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  churchId: text("church_id").notNull().unique(),
  name: text("name").notNull(),
  initials: text("initials").notNull(),
  groupName: text("group_name").notNull().default("General"),
  phone: text("phone").notNull().default(""),
  email: text("email"),
  gender: text("gender"),
  birthDate: text("birth_date"),
  maritalStatus: text("marital_status"),
  weddingDate: text("wedding_date"),
  address: text("address"),
  hometown: text("hometown"),
  occupation: text("occupation"),
  membershipType: text("membership_type"),
  baptismStatus: text("baptism_status"),
  emergencyName: text("emergency_name"),
  emergencyPhone: text("emergency_phone"),
  notes: text("notes"),
  profilePhotoKey: text("profile_photo_key"),
  status: text("status").notNull().default("Active"),
  joinedAt: text("joined_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const users = sqliteTable("users", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  role: text("role").notNull().default("ministry_leader"),
  campus: text("campus").notNull().default("Grace Centre"),
  status: text("status").notNull().default("Active"),
  memberId: integer("member_id").references(() => members.id, { onDelete: "set null" }),
  mfaEnabled: integer("mfa_enabled", { mode: "boolean" }).notNull().default(false),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  lastActiveAt: text("last_active_at"),
});

export const mobileDevices = sqliteTable("mobile_devices", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userId: integer("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  tokenHash: text("token_hash").notNull().unique(),
  deviceName: text("device_name").notNull().default("ChurchFlow Mobile"),
  status: text("status").notNull().default("Active"),
  lastUsedAt: text("last_used_at"),
  expiresAt: text("expires_at").notNull(),
  createdByUserId: integer("created_by_user_id").references(() => users.id, { onDelete: "set null" }),
  createdByName: text("created_by_name").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  revokedAt: text("revoked_at"),
});

export const households = sqliteTable("households", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  householdCode: text("household_code").notNull().unique(),
  name: text("name").notNull(),
  address: text("address").notNull().default(""),
  primaryPhone: text("primary_phone").notNull().default(""),
  campus: text("campus").notNull().default("Grace Centre"),
  pastoralZone: text("pastoral_zone").notNull().default("Unassigned"),
  status: text("status").notNull().default("Active"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const householdMembers = sqliteTable("household_members", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  householdId: integer("household_id").notNull().references(() => households.id, { onDelete: "cascade" }),
  memberId: integer("member_id").notNull().references(() => members.id, { onDelete: "cascade" }),
  relationship: text("relationship").notNull().default("Member"),
  isPrimary: integer("is_primary", { mode: "boolean" }).notNull().default(false),
});

export const organisationUnits = sqliteTable("organisation_units", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull().unique(),
  type: text("type").notNull().default("Ministry"),
  leaderName: text("leader_name").notNull().default("Unassigned"),
  memberCount: integer("member_count").notNull().default(0),
  meetingSchedule: text("meeting_schedule").notNull().default("To be scheduled"),
  campus: text("campus").notNull().default("Grace Centre"),
  status: text("status").notNull().default("Active"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const leadershipAppointments = sqliteTable("leadership_appointments", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  appointmentCode: text("appointment_code").notNull().unique(),
  memberId: integer("member_id").references(() => members.id, { onDelete: "set null" }),
  leaderName: text("leader_name").notNull(),
  title: text("title").notNull(),
  leadershipLevel: text("leadership_level").notNull(),
  ministry: text("ministry").notNull(),
  campus: text("campus").notNull().default("Grace Centre"),
  startDate: text("start_date").notNull(),
  termEndDate: text("term_end_date"),
  status: text("status").notNull().default("Active"),
  createdByUserId: integer("created_by_user_id").references(() => users.id, { onDelete: "set null" }),
  createdByName: text("created_by_name").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const volunteers = sqliteTable("volunteers", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  volunteerCode: text("volunteer_code").notNull().unique(),
  memberId: integer("member_id").references(() => members.id, { onDelete: "set null" }),
  name: text("name").notNull(),
  phone: text("phone").notNull().default(""),
  skills: text("skills").notNull().default(""),
  availability: text("availability").notNull().default("Sundays"),
  ministryPreference: text("ministry_preference").notNull().default("General Service"),
  safeguardingStatus: text("safeguarding_status").notNull().default("Not required"),
  status: text("status").notNull().default("Active"),
  joinedAt: text("joined_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  createdByUserId: integer("created_by_user_id").references(() => users.id, { onDelete: "set null" }),
  createdByName: text("created_by_name").notNull(),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const volunteerAssignments = sqliteTable("volunteer_assignments", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  volunteerId: integer("volunteer_id").notNull().references(() => volunteers.id, { onDelete: "cascade" }),
  eventId: integer("event_id"),
  assignmentDate: text("assignment_date").notNull(),
  serviceName: text("service_name").notNull(),
  teamName: text("team_name").notNull(),
  role: text("role").notNull(),
  callTime: text("call_time").notNull(),
  status: text("status").notNull().default("Assigned"),
  createdByUserId: integer("created_by_user_id").references(() => users.id, { onDelete: "set null" }),
  createdByName: text("created_by_name").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const attendanceSessions = sqliteTable("attendance_sessions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  sessionCode: text("session_code").notNull().unique(),
  title: text("title").notNull(),
  serviceType: text("service_type").notNull().default("Sunday Service"),
  serviceDate: text("service_date").notNull(),
  startTime: text("start_time").notNull(),
  campus: text("campus").notNull().default("Grace Centre"),
  venue: text("venue").notNull().default("Main Auditorium"),
  status: text("status").notNull().default("Scheduled"),
  expectedCount: integer("expected_count").notNull().default(0),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const attendanceRecords = sqliteTable("attendance_records", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  sessionId: integer("session_id").notNull().references(() => attendanceSessions.id, { onDelete: "cascade" }),
  memberId: integer("member_id").references(() => members.id, { onDelete: "set null" }),
  personType: text("person_type").notNull().default("Member"),
  visitorName: text("visitor_name"),
  attendanceStatus: text("attendance_status").notNull().default("Present"),
  checkInMethod: text("check_in_method").notNull().default("Manual"),
  checkedInAt: text("checked_in_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  notes: text("notes"),
}, (table) => [
  uniqueIndex("attendance_session_member_unique").on(table.sessionId, table.memberId),
]);

export const financeFunds = sqliteTable("finance_funds", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull().unique(),
  code: text("code").notNull().unique(),
  purpose: text("purpose").notNull().default("Church operations"),
  status: text("status").notNull().default("Active"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const financeTransactions = sqliteTable("finance_transactions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  reference: text("reference").notNull().unique(),
  type: text("type").notNull(),
  category: text("category").notNull(),
  fundId: integer("fund_id").notNull().references(() => financeFunds.id),
  amountPesewas: integer("amount_pesewas").notNull(),
  transactionDate: text("transaction_date").notNull(),
  paymentMethod: text("payment_method").notNull().default("Cash"),
  description: text("description").notNull(),
  payerPayee: text("payer_payee"),
  receiptNumber: text("receipt_number"),
  status: text("status").notNull().default("Pending"),
  recordedBy: text("recorded_by").notNull(),
  recordedByUserId: integer("recorded_by_user_id").references(() => users.id, { onDelete: "set null" }),
  recordedByEmail: text("recorded_by_email"),
  approvedBy: text("approved_by"),
  approvedByUserId: integer("approved_by_user_id").references(() => users.id, { onDelete: "set null" }),
  approvedByEmail: text("approved_by_email"),
  approvedAt: text("approved_at"),
  decisionReason: text("decision_reason"),
  reversalOfId: integer("reversal_of_id"),
  reversalReason: text("reversal_reason"),
  immutableAt: text("immutable_at"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const welfareRequests = sqliteTable("welfare_requests", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  requestCode: text("request_code").notNull().unique(),
  memberId: integer("member_id").references(() => members.id, { onDelete: "set null" }),
  beneficiaryName: text("beneficiary_name").notNull(),
  beneficiaryPhone: text("beneficiary_phone"),
  supportType: text("support_type").notNull(),
  amountRequestedPesewas: integer("amount_requested_pesewas").notNull(),
  amountApprovedPesewas: integer("amount_approved_pesewas"),
  urgency: text("urgency").notNull().default("Normal"),
  assessmentSummary: text("assessment_summary").notNull(),
  assignedCommittee: text("assigned_committee").notNull().default("Welfare Committee"),
  decisionReason: text("decision_reason"),
  status: text("status").notNull().default("Pending assessment"),
  financeTransactionId: integer("finance_transaction_id").references(() => financeTransactions.id, { onDelete: "set null" }),
  requestedByUserId: integer("requested_by_user_id").references(() => users.id, { onDelete: "set null" }),
  requestedByName: text("requested_by_name").notNull(),
  reviewedByUserId: integer("reviewed_by_user_id").references(() => users.id, { onDelete: "set null" }),
  reviewedByName: text("reviewed_by_name"),
  reviewedAt: text("reviewed_at"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const payrollStaff = sqliteTable("payroll_staff", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  staffCode: text("staff_code").notNull().unique(),
  memberId: integer("member_id").references(() => members.id, { onDelete: "set null" }),
  fullName: text("full_name").notNull(),
  jobTitle: text("job_title").notNull(),
  department: text("department").notNull(),
  employmentType: text("employment_type").notNull().default("Full-time"),
  bankName: text("bank_name"),
  bankAccountLast4: text("bank_account_last4"),
  mobileMoneyNumber: text("mobile_money_number"),
  baseSalaryPesewas: integer("base_salary_pesewas").notNull(),
  recurringAllowancePesewas: integer("recurring_allowance_pesewas").notNull().default(0),
  recurringDeductionPesewas: integer("recurring_deduction_pesewas").notNull().default(0),
  status: text("status").notNull().default("Active"),
  createdByUserId: integer("created_by_user_id").references(() => users.id, { onDelete: "set null" }),
  createdByName: text("created_by_name").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const payrollRuns = sqliteTable("payroll_runs", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  runCode: text("run_code").notNull().unique(),
  payPeriod: text("pay_period").notNull(),
  paymentDate: text("payment_date").notNull(),
  status: text("status").notNull().default("Draft"),
  grossPesewas: integer("gross_pesewas").notNull().default(0),
  deductionsPesewas: integer("deductions_pesewas").notNull().default(0),
  netPesewas: integer("net_pesewas").notNull().default(0),
  preparedByUserId: integer("prepared_by_user_id").references(() => users.id, { onDelete: "set null" }),
  preparedByName: text("prepared_by_name").notNull(),
  approvedByUserId: integer("approved_by_user_id").references(() => users.id, { onDelete: "set null" }),
  approvedByName: text("approved_by_name"),
  approvedAt: text("approved_at"),
  decisionReason: text("decision_reason"),
  financeTransactionId: integer("finance_transaction_id").references(() => financeTransactions.id, { onDelete: "set null" }),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const payrollItems = sqliteTable("payroll_items", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  payrollRunId: integer("payroll_run_id").notNull().references(() => payrollRuns.id, { onDelete: "cascade" }),
  staffId: integer("staff_id").notNull().references(() => payrollStaff.id),
  baseSalaryPesewas: integer("base_salary_pesewas").notNull(),
  allowancesPesewas: integer("allowances_pesewas").notNull().default(0),
  deductionsPesewas: integer("deductions_pesewas").notNull().default(0),
  netPayPesewas: integer("net_pay_pesewas").notNull(),
  paymentStatus: text("payment_status").notNull().default("Pending"),
});

export const generatedRecords = sqliteTable("generated_records", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  recordCode: text("record_code").notNull().unique(),
  recordType: text("record_type").notNull(),
  templateType: text("template_type").notNull(),
  memberId: integer("member_id").references(() => members.id, { onDelete: "set null" }),
  subjectName: text("subject_name").notNull(),
  eventDate: text("event_date"),
  fieldsJson: text("fields_json").notNull().default("{}"),
  status: text("status").notNull().default("Draft"),
  issuedAt: text("issued_at"),
  issuedByUserId: integer("issued_by_user_id").references(() => users.id, { onDelete: "set null" }),
  issuedByName: text("issued_by_name"),
  createdByUserId: integer("created_by_user_id").references(() => users.id, { onDelete: "set null" }),
  createdByName: text("created_by_name").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const archiveAssets = sqliteTable("archive_assets", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  assetCode: text("asset_code").notNull().unique(),
  assetType: text("asset_type").notNull(),
  title: text("title").notNull(),
  description: text("description"),
  speakerAuthor: text("speaker_author"),
  ministry: text("ministry").notNull().default("Church-wide"),
  eventDate: text("event_date"),
  scriptureReference: text("scripture_reference"),
  tags: text("tags").notNull().default(""),
  fileKey: text("file_key"),
  fileName: text("file_name"),
  contentType: text("content_type"),
  fileSize: integer("file_size"),
  externalUrl: text("external_url"),
  visibility: text("visibility").notNull().default("Internal"),
  status: text("status").notNull().default("Published"),
  uploadedByUserId: integer("uploaded_by_user_id").references(() => users.id, { onDelete: "set null" }),
  uploadedByName: text("uploaded_by_name").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const churchEvents = sqliteTable("church_events", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  eventCode: text("event_code").notNull().unique(),
  title: text("title").notNull(),
  eventType: text("event_type").notNull().default("Service"),
  startDate: text("start_date").notNull(),
  startTime: text("start_time").notNull(),
  endTime: text("end_time"),
  campus: text("campus").notNull().default("Grace Centre"),
  venue: text("venue").notNull().default("Main Auditorium"),
  coordinator: text("coordinator").notNull().default("Unassigned"),
  expectedAttendance: integer("expected_attendance").notNull().default(0),
  status: text("status").notNull().default("Planning"),
  attendanceSessionId: integer("attendance_session_id").references(() => attendanceSessions.id, { onDelete: "set null" }),
  notes: text("notes"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const eventProgrammeItems = sqliteTable("event_programme_items", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  eventId: integer("event_id").notNull().references(() => churchEvents.id, { onDelete: "cascade" }),
  sequence: integer("sequence").notNull(),
  title: text("title").notNull(),
  owner: text("owner").notNull().default("Unassigned"),
  durationMinutes: integer("duration_minutes").notNull().default(10),
  status: text("status").notNull().default("Ready"),
});

export const eventAssignments = sqliteTable("event_assignments", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  eventId: integer("event_id").notNull().references(() => churchEvents.id, { onDelete: "cascade" }),
  teamName: text("team_name").notNull(),
  leaderName: text("leader_name").notNull().default("Unassigned"),
  requiredCount: integer("required_count").notNull().default(1),
  confirmedCount: integer("confirmed_count").notNull().default(0),
  status: text("status").notNull().default("Pending"),
});

export const careCases = sqliteTable("care_cases", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  caseCode: text("case_code").notNull().unique(),
  memberId: integer("member_id").references(() => members.id, { onDelete: "set null" }),
  personName: text("person_name").notNull(),
  personPhone: text("person_phone"),
  personType: text("person_type").notNull().default("Member"),
  caseType: text("case_type").notNull(),
  source: text("source").notNull().default("Church office"),
  priority: text("priority").notNull().default("Normal"),
  stage: text("stage").notNull().default("New"),
  assignedTo: text("assigned_to").notNull().default("Pastoral Care Team"),
  nextActionDate: text("next_action_date"),
  summary: text("summary").notNull(),
  sensitiveNotes: text("sensitive_notes"),
  isConfidential: integer("is_confidential", { mode: "boolean" }).notNull().default(false),
  status: text("status").notNull().default("Open"),
  createdBy: text("created_by").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const careActivities = sqliteTable("care_activities", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  caseId: integer("case_id").notNull().references(() => careCases.id, { onDelete: "cascade" }),
  activityType: text("activity_type").notNull(),
  note: text("note").notNull(),
  outcome: text("outcome"),
  completedBy: text("completed_by").notNull(),
  completedAt: text("completed_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const communicationCampaigns = sqliteTable("communication_campaigns", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  campaignCode: text("campaign_code").notNull().unique(),
  name: text("name").notNull(),
  channel: text("channel").notNull(),
  audience: text("audience").notNull(),
  subject: text("subject"),
  message: text("message").notNull(),
  status: text("status").notNull().default("Draft"),
  scheduledAt: text("scheduled_at"),
  sentAt: text("sent_at"),
  recipientCount: integer("recipient_count").notNull().default(0),
  deliveredCount: integer("delivered_count").notNull().default(0),
  failedCount: integer("failed_count").notNull().default(0),
  createdByUserId: integer("created_by_user_id").references(() => users.id, { onDelete: "set null" }),
  createdByName: text("created_by_name").notNull(),
  createdByEmail: text("created_by_email").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const celebrationReminders = sqliteTable("celebration_reminders", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  reminderCode: text("reminder_code").notNull().unique(),
  memberId: integer("member_id").notNull().references(() => members.id, { onDelete: "cascade" }),
  celebrationType: text("celebration_type").notNull(),
  occurrenceDate: text("occurrence_date").notNull(),
  channel: text("channel").notNull().default("In-app"),
  status: text("status").notNull().default("Prepared"),
  campaignId: integer("campaign_id").references(() => communicationCampaigns.id, { onDelete: "set null" }),
  preparedByUserId: integer("prepared_by_user_id").references(() => users.id, { onDelete: "set null" }),
  preparedByName: text("prepared_by_name").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  uniqueIndex("celebration_member_occurrence_unique").on(table.memberId, table.celebrationType, table.occurrenceDate),
]);

export const auditLogs = sqliteTable("audit_logs", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  actorEmail: text("actor_email").notNull(),
  actorName: text("actor_name").notNull(),
  action: text("action").notNull(),
  entityType: text("entity_type").notNull(),
  entityId: text("entity_id").notNull(),
  detail: text("detail"),
  requestId: text("request_id"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
